### ISSUE TITLE
helm: no output

### ISSUE THREAD

**Issue by beacomni** [snyk-labs/helm-snyk#38]
Successful install of chart with 

`helm pull stable/redis --untar=true --untardir=stable_redis_pull`
`helm install stable-redis-from-pull ./stable_redis_pull/redis/`

```
ubuntu@:~$ helm list
NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
stable-redis-from-pull  sumologic       1               2020-04-08 16:40:44.99386781 +0000 UTC  deployed        redis-10.5.7    5.0.7
```
```
ubuntu@:~$ helm snyk test  ./stable_redis_pull/redis/
/bin/sh: 1: helm: not found

try to run 'helm template ./stable_redis_pull/redis/' first!
```
contents of the directory seem to contain templated chart:
```
ubuntu@:~$ ls ./stable_redis_pull/redis/
Chart.yaml  ci  README.md  templates  values-production.yaml  values.schema.json  values.yaml
```

**Comment by beacomni** [comment]
Update to this issue -- it's a misleading error message `try to run 'helm template ./stable_redis_pull/redis/' first!`. The important element was the earlier `/bin/sh: 1: helm: not found`. Since I was using microk8s.helm3, and trying to alias in bash with `alias helm=microk8s.helm3`, /bin/sh was not seeing the alias. It may be possible to workaround by 

make a file helm,
```
#!/bin/sh
microk8s.helm3 $@ 
```

then `chmod ugoa+rwx helm; mv helm /bin/helm`

**Comment by agranado2k** [comment]
Hi @beacomni,

We've just released a new plugin version that solve this issue. Could you update the plugin with follow command, please?

```
helm plugin update snyk
```

**Comment by beacomni** [comment]
Thank you for the MR to address this and https://github.com/snyk-labs/helm-snyk/issues/37. However, the issue of no output is still occurring. I think the changes only addressed #37. 

Still getting no output:

```
ubuntu@ip-:~$ helm pull stable/redis --untar=true --untardir=stable_redis_pull
ubuntu@ip-:~$ helm snyk test stable_redis_pull/redis/

ubuntu@ip-:~$

```

```
~$ helm snyk --version
1.2.5
```

**Comment by agranado2k** [comment]
Hi @beacomni,

I saw that this problem is because the script `helm` that you created:
```shell
#!/bin/sh
microk8s.helm3 $@ 
```
Is returning a no formatted output as a long string. And because of the way the helm-snyk works, it needs the template format to find the correct images. To avoid that you can make a small change in the script to:
```shell
#!/bin/sh
set -euf
output=$(microk8s.helm3 $@)
echo "$output" 
```
It will work fine! 

I hope to helped you to solve this problem. Let me know if you have any other problem.

**Comment by beacomni** [comment]
Thanks @agranado2k for the follow up, I was able to successfully get a report on the example provided from the doc. Much appreciated.
